
name: Build and Deploy

on:
  push:
    branches:
    - master
    - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.6'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: make build
    - name: Run vet & lint
      run: |
        go vet .
        golint .
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch Deploy Repo
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        token: ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN }}
        repository: toksikk/deploy-gidbig
        event-type: deploy
